services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Infrastructure\:
    lazy: true
    resource: '../../src/Infrastructure/*'
    exclude: '../../src/Infrastructure/{Controllers,Migrations,Kernel.php}'

  Infrastructure\Controllers\:
    resource: '../../src/Infrastructure/Controllers'
    tags: [ 'controller.service_arguments' ]
