products_list:
  controller: Infrastructure\Controllers\Product\GetProductsListController
  path: /products/list
  methods: GET|HEAD
#  resource: Infrastructure\Controllers/GetProductsList
#  type: rest
